
- name: Load Administrator profile using Scheduled Tasks
  hosts: vision_servers
  gather_facts: true
  tasks:
    - name: Create a local user
      ansible.windows.win_user:
        name: svc-vision-account
        password: "Str0ngP@ssw0rd2025!"
        password_never_expires: true
        user_cannot_change_password: true
        account_disabled: false

    - name: Add domain user to local administrators group
      ansible.windows.win_group_membership:
        name: Administrators
        members:
          - development\admintt
        state: present

    # - name: Load profile for domain user
    #   win_shell: runas /user:development\admintt /profile cmd.exe
    #   register: profile_load_result

    # - name: Debug profile load output
    #   debug:
    #     var: profile_load_result.stdout



