- name: Create local admin user on Windows
  hosts: vision_servers
  gather_facts: true
  vars:
    windows_domain: "{{ ansible_hostname }}"
    profile_marker: C:\Users\Administrator\profile_loaded.txt
  tasks:

    - name: Create a local user
      ansible.windows.win_user:
        name: svc-vision-account
        password: "Str0ngP@ssw0rd2025!"
        password_never_expires: true
        user_cannot_change_password: true
        account_disabled: false

    - name: Add user to Administrators group (correct format)
      ansible.windows.win_group_membership:
        name: Administrators
        members:
          - '{{ windows_domain }}\svc-vision-account'
        state: present
        
    - name: Ensure C:\Temp directory exists
      ansible.windows.win_file:
        path: C:\Temp
        state: directory

    - name: Check if Administrator profile already exists
      ansible.windows.win_stat:
        path: "{{ profile_marker }}"
      register: profile_status

    - name: Create profile-loading script
      ansible.windows.win_copy:
        content: 'echo Profile has been loaded > "{{ profile_marker }}"'
        dest: C:\Temp\load_admin_profile.bat
      when: not profile_status.stat.exists

    - name: Run script once as Administrator to load profile
      ansible.windows.win_command: schtasks /create /tn LoadAdminProfile /tr "C:\\Temp\\load_admin_profile.bat" /sc once /st 00:00 /ru Administrator /rp "{{ ansible_password }}"
      when: not profile_status.stat.exists

    - name: Run the scheduled task
      ansible.windows.win_command: schtasks /run /tn LoadAdminProfile
      when: not profile_status.stat.exists

    - name: Wait for profile to initialize
      pause:
        seconds: 5
      when: not profile_status.stat.exists

    - name: Delete the scheduled task
      ansible.windows.win_command: schtasks /delete /tn LoadAdminProfile /f
      when: not profile_status.stat.exists
